import { expect, test } from 'playwright/test'

test('the public petition is readable and starts the signing flow', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Petition for humane stray dog public-safety action/i }).first()).toBeVisible()
  await expect(page.getByRole('main').getByText('Amballur Grama Panchayat', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: /Continue to sign/i }).click()
  await expect(page.getByRole('heading', { name: /Your details/i })).toBeVisible()
  await expect(page.getByLabel(/Ward/i)).toHaveValue('')
  await page.getByLabel(/Full name/i).fill('Anu Thomas')
  await page.getByLabel(/House name or number/i).fill('Green Villa')
  await page.getByLabel(/Ward/i).selectOption({ label: '16 — Ward 16' })
  await page.getByRole('button', { name: /^Continue$/i }).click()
  await expect(page.getByRole('heading', { name: /Add your signature/i })).toBeVisible()
  const canvas = page.locator('canvas')
  const box = await canvas.boundingBox()
  if (!box) throw new Error('Signature canvas is not visible')
  await page.mouse.move(box.x + 30, box.y + 95)
  await page.mouse.down()
  await page.mouse.move(box.x + 90, box.y + 55)
  await page.mouse.move(box.x + 150, box.y + 110)
  await page.mouse.up()
  await page.getByRole('button', { name: /Save signature/i }).click()
  await expect(page.getByText(/Signature captured/i)).toBeVisible()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: /^Continue$/i }).click()
  await expect(page.getByRole('heading', { name: /Review before submitting/i })).toBeVisible()
})
